### ISSUE TITLE
Failed to login (US region)

### ISSUE THREAD

**Issue by jerryc05** [RobertD502/home-assistant-petkit#25]
Hi my account is an US regions and when I try to login via hass integration, I got this error:
`Unknown PetKit Error: PetKit Error 125: The phone number is not registered`.

I did not check `asia` or `china` account checkboxes.

```
Traceback (most recent call last):
 File "/config/custom_components/petkit/util.py", line 41, in async_validate_api
 devices_query = await client.get_device_roster()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/petkitaio/petkit_client.py", line 170, in get_device_roster
 await self.check_token()
 File "/usr/local/lib/python3.11/site-packages/petkitaio/petkit_client.py", line 144, in check_token
 await self.login()
 File "/usr/local/lib/python3.11/site-packages/petkitaio/petkit_client.py", line 130, in login
 response = await self._post(login_url, headers, data)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/petkitaio/petkit_client.py", line 404, in _post
 return await self._response(resp)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/petkitaio/petkit_client.py", line 426, in _response
 raise PetKitError(f'PetKit Error {code}: {response["error"]["msg"]}')
petkitaio.exceptions.PetKitError: PetKit Error 125: The phone number is not registered
```

**Comment by RobertD502** [comment]
That error message is only sent by PetKit servers when the China region is being used which is weird considering you didn't check that box. Mind sending me a personal message on discord?
