### ISSUE TITLE
Error adding entity None for domain binary_sensor with platform petkit

### ISSUE THREAD

**Issue by adriannow** [RobertD502/home-assistant-petkit#80]
Hello, I'm able to successfully add Petkit account, but no devices are found later on. I enabled debug, and here seems to be the problem: 

```
2024-08-28 14:59:00.366 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up petkit.binary_sensor
2024-08-28 14:59:00.366 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity None for domain binary_sensor with platform petkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 768, in _async_add_entity
    if self.config_entry and (device_info := entity.device_info):
                                             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/binary_sensor.py", line 169, in device_info
    "name": self.feeder_data.data['name'],
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
2024-08-28 14:59:00.370 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity None for domain binary_sensor with platform petkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 768, in _async_add_entity
    if self.config_entry and (device_info := entity.device_info):
                                             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/binary_sensor.py", line 251, in device_info
    "name": self.feeder_data.data['name'],
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
2024-08-28 14:59:00.370 INFO (MainThread) [homeassistant.components.button] Setting up petkit.button
2024-08-28 14:59:00.370 ERROR (MainThread) [homeassistant.components.button] Error adding entity None for domain button with platform petkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 768, in _async_add_entity
    if self.config_entry and (device_info := entity.device_info):
                                             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/button.py", line 200, in device_info
    "name": self.feeder_data.data['name'],
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
2024-08-28 14:59:00.373 ERROR (MainThread) [homeassistant.components.button] Error adding entity None for domain button with platform petkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 768, in _async_add_entity
    if self.config_entry and (device_info := entity.device_info):
                                             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/button.py", line 268, in device_info
    "name": self.feeder_data.data['name'],
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
2024-08-28 14:59:00.374 INFO (MainThread) [homeassistant.components.fan] Setting up petkit.fan
2024-08-28 14:59:00.374 INFO (MainThread) [homeassistant.components.number] Setting up petkit.number
2024-08-28 14:59:00.374 INFO (MainThread) [homeassistant.components.select] Setting up petkit.select
```

**Comment by RobertD502** [comment]
Did you enable debug logging, for the integration, via the Home Assistant UI? If so, after enabling debugging, restarting Home Assistant, and then disabling debugging for the integration, it should have downloaded a log file to your device. This log file will contain data from the update coordinator, which holds data from the devices the integration retrieved from the PetKit API and would allow me to investigate what is going on.

**Comment by adriannow** [comment]
@RobertD502 sure - full output is quite long however. I'll try to paste the important parts. 

So first mention regarding integration and device seems to be - which is I think the part you wanted to find in logs: 

```2024-08-28 22:05:15.379 DEBUG (MainThread) [custom_components.petkit] Found the following PetKit devices/pets: PetKitData(user_id='200019911', feeders={400028755: Feeder(id=400028755, data={'id': 400028755, 'mac': 'a842e3efde9c', 'sn': '20231201G10124', 'secret': 'XXX', 'createdAt': '2024-08-28T11:37:44.922+0000', 'hardware': 1, 'firmware': '1.262', 'firmwareDetails': [{'module': 'userbin', 'version': 2332001}, {'module': 'lans', 'version': 1001}], 'timezone': 2.0, 'signupAt': '2024-08-28T11:42:11.121+0000', 'locale': 'Europe/Warsaw', 'user': {'id': '200019911', 'nick': 'User811037', 'gender': 3, 'avatar': 'https://sandbox-img5.petkit.cn/banner/2022/10/13/6347d75a44ad08000b011e7dDzwc693i5', 'point': {'honour': 'LV0', 'rank': 0, 'growth': 0, 'icon': 'http://img5-us.petkit.cn/misc/point/n0', 'icon2': 'http://img5-us.petkit.cn/misc/point/l0', 'startGrowth': 0, 'endGrowth': 50}}, 'shareOpen': 0, 'autoUpgrade': 1, 'relation': {'userId': '200019911'}, 'btMac': 'a842e3efde9e', 'typeCode': 1, 'settings': {'feedNotify': 1, 'foodNotify': 1, 'foodWarn': 0, 'foodWarnRange': [480, 1200], 'lowBatteryNotify': 1, 'desiccantNotify': 1, 'manualLock': 0, 'lightMode': 1, 'lightRange': [0, 1440], 'factor': 10, 'lightConfig': 1, 'lightMultiRange': [], 'feedSound': 1, 'colorSetting': 3, 'controlSettings': 1}, 'desc': 'No feeding plan.', 'multiFeed': True, 'multiConfig': True, 'multiFeedItem': {'feedDailyList': [{'suspended': 0, 'repeats': 1, 'items': []}, {'suspended': 0, 'repeats': 2, 'items': []}, {'suspended': 0, 'repeats': 3, 'items': []}, {'suspended': 0, 'repeats': 4, 'items': []}, {'suspended': 0, 'repeats': 5, 'items': []}, {'suspended': 0, 'repeats': 6, 'items': []}, {'suspended': 0, 'repeats': 7, 'items': []}], 'isExecuted': 1, 'userId': '1'}, 'state': {'wifi': {'ssid': 'OCZO', 'bssid': '04d9f5c5e798', 'rsq': -45}, 'pim': 1, 'ota': 0, 'overall': 1, 'batteryStatus': 0, 'runtime': 0, 'batteryPower': 4, 'food': 1, 'feedState': {'realAmountTotal': 180, 'planAmountTotal': 0, 'addAmountTotal': 180, 'planRealAmountTotal': 0, 'times': 9, 'feedTimes': {'49436': 1, '49522': 1, '49638': 1, '56777': 1, '56855': 1, '56942': 1, '57742': 1, '57768': 1, '77686': 1}}, 'desiccantLeftDays': 29, 'door': 0, 'feeding': 0, 'desiccantTime': 0}}, type='d4', sound_list={}, last_manual_feed_id=None)}, litter_boxes={}, water_fountains={}, pets={}, purifiers={})
2024-08-28 22:05:15.379 DEBUG (MainThread) [custom_components.petkit] Finished fetching petkit data in 1.117 seconds (success: True)
```
(only replaced secret credentials)

The rest of the output regarding Petkit is the errors I added in the first message.

**Comment by RobertD502** [comment]
Go into the PETKIT app and give the feeder a name. As of now, the API isn't returning a feeder name key at all.

**Comment by adriannow** [comment]
Adding name to the device worked :)
