### ISSUE TITLE
Purobot Ultra integration

### ISSUE THREAD

**Issue by artiomchi** [RobertD502/home-assistant-petkit#98]
Hi All

I just got an Purobot Ultra - the kickstarter backed AI litter box, and would love to get it working with the integration. Please let me know what I need to do to make it happen. Are there any guidelines on how to build an integration?

It's WiFi powered, if that helps. Happy to help out with what I can, including implementation, but I'd probably need some guidance

Thanks!

**Comment by Jezza34000** [comment]
Hi ! i'm working on it with @Cyrelion my fork had partial support for T6 (Purobot ULTRA) if you want to try or to help us :-) https://github.com/Jezza34000/home-assistant-petkit

**Comment by Cyrelion** [comment]
@Jezza34000 has also build the support for the EverSweet MAX 😍 best man

**Comment by JrothSKV** [comment]
I'd love to give it a try.  Can you give a hint on how to get it installed?  Adding that url as a custom repo in HACS works, but as soon as you click download it throws this error.  I removed the original integration before adding this repo.

[32m2024-11-24 14:22:05.767 INFO (MainThread) [custom_components.hacs] Starting download, fd00772[0m
[32m2024-11-24 14:22:05.767 INFO (MainThread) [custom_components.hacs] <Integration Jezza34000/home-assistant-petkit> Running pre installation steps[0m
[32m2024-11-24 14:22:05.767 INFO (MainThread) [custom_components.hacs] <Integration Jezza34000/home-assistant-petkit> Pre installation steps completed[0m
[32m2024-11-24 14:22:05.767 INFO (MainThread) [custom_components.hacs] <Integration Jezza34000/home-assistant-petkit> Running installation steps[0m
[31m2024-11-24 14:22:08.217 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/Jezza34000/home-assistant-petkit/releases/download/fd00772/petkit.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/Jezza34000/home-assistant-petkit/releases/download/fd00772/petkit.zip[0m
[31m2024-11-24 14:22:08.218 ERROR (MainThread) [custom_components.hacs] <Integration Jezza34000/home-assistant-petkit> Failed to download https://github.com/Jezza34000/home-assistant-petkit/releases/download/tags/fd00772/petkit.zip[0m
[31m2024-11-24 14:22:08.218 ERROR (MainThread) [custom_components.hacs] <Integration Jezza34000/home-assistant-petkit> Downloading Jezza34000/home-assistant-petkit with version fd00772 failed with (Could not download, see log for details)[0m


> Hi ! i'm working on it with @Cyrelion my fork had partial support for T6 (Purobot ULTRA) if you want to try or to help us :-) https://github.com/Jezza34000/home-assistant-petkit

**Comment by Cyrelion** [comment]
At the moment there is no released version yet. Just download it via GitHub and exchange the files in the petkit directory/custom_components directory via file browser/visual studio.

So yet not an in-place replacement. But he’s working on that too

**Comment by JrothSKV** [comment]
Ok gotcha.  Reinstalled and configured the original integration, overwrote the existing files with the extracted zip, restarted HA, and got the following.  Is there an update or mod for the petkitaio package needed?

```
Setup failed for custom integration 'petkit': Unable to import component: cannot import name 'FountainCommand' from 'petkitaio.constants' (/usr/local/lib/python3.12/site-packages/petkitaio/constants.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/petkit/__init__.py", line 9, in <module>
    from .const import DOMAIN, LOGGER, PETKIT_COORDINATOR, PLATFORMS, POLLING_INTERVAL, REGION, TIMEZONE, UPDATE_LISTENER
  File "/config/custom_components/petkit/const.py", line 8, in <module>
    from petkitaio.constants import FountainCommand, PurifierCommand
ImportError: cannot import name 'FountainCommand' from 'petkitaio.constants' (/usr/local/lib/python3.12/site-packages/petkitaio/constants.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/petkit/__init__.py", line 9, in <module>
    from .const import DOMAIN, LOGGER, PETKIT_COORDINATOR, PLATFORMS, POLLING_INTERVAL, REGION, TIMEZONE, UPDATE_LISTENER
  File "/config/custom_components/petkit/const.py", line 8, in <module>
    from petkitaio.constants import FountainCommand, PurifierCommand
ImportError: cannot import name 'FountainCommand' from 'petkitaio.constants' (/usr/local/lib/python3.12/site-packages/petkitaio/constants.py)
```


> At the moment there is no released version yet. Just download it via GitHub and exchange the files in the petkit directory/custom_components directory via file browser/visual studio.
> 
> So yet not an in-place replacement. But he’s working on that too

**Comment by Jezza34000** [comment]
Hi @JrothSKV open an issue on my repo, to avoid being off-topic on this thread. I will explain you how to fix it
